version: "3.8"

services:
  mysql:
    image: mysql:5.7
    command: --character-set-server=utf8mb4
    volumes:
      - shuffle-mysql-data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: shuffle
    ports:
      - 3306:3306

volumes:
  shuffle-mysql-data: