# Generated by Django 3.2.6 on 2021-08-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joke',
            name='lang',
            field=models.CharField(choices=[('ENG', 'English'), ('RU', 'Русский')], default='RU', max_length=4),
        ),
    ]
