# Generated by Django 3.2.6 on 2021-08-14 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0002_joke_lang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joke',
            name='downvotes',
        ),
        migrations.RemoveField(
            model_name='joke',
            name='upvotes',
        ),
        migrations.AddField(
            model_name='joke',
            name='capitalize',
            field=models.BooleanField(default=True, verbose_name='Capitalize punchline when inserting a new one'),
        ),
        migrations.AddField(
            model_name='joke',
            name='use_as_destination',
            field=models.BooleanField(default=True, verbose_name='Use this joke as a punchline destination'),
        ),
        migrations.AddField(
            model_name='joke',
            name='use_as_source',
            field=models.BooleanField(default=True, verbose_name='Use this joke as a punchline source'),
        ),
        migrations.CreateModel(
            name='CombinedJoke',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combined_as_destination', to='jokes.joke')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combined_as_source', to='jokes.joke')),
            ],
        ),
    ]
