# Generated by Django 3.2.6 on 2022-08-26 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0003_auto_20210814_1340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='combinedjoke',
            options={'ordering': ['-upvotes']},
        ),
    ]
